Repository BinaryStudioAcademy/bsa-2020-DaLi, pull requests merged in 2020-08, with the labels that each got.

#54 Feature/account settings page
  client/src/containers/AccountSettingsContainer/AccountSettingsContainer.js
  client/src/containers/AccountSettingsContainer/helper.js
  client/src/containers/AccountSettingsContainer/index.js
  client/src/containers/AccountSettingsContainer/styles.js
  client/src/containers/index.js
  client/src/pages/AccountSettingsPage/AccountSettingsPage.js
  client/src/pages/index.js
  client/src/routes/routes.js
Labels: enhancement

#55 fix chart containers to show it in visualization container
  client/src/components/BarChart/BarChart.js
  client/src/components/LineChart/LineChart.js
  client/src/containers/BarChartContainer/BarChartContainer.js
  client/src/containers/LineChartContainer/LineChartContainer.js
  client/src/containers/VisualizationsListContainer/reducer.js
  client/yarn.lock
Labels: fix

#53 removed routes, service and repository for viualisation config
  server/src/models/index.js
  server/src/models/visualizationConfig.js
  server/src/repositories/visualizationConfigRepository.js
  server/src/routes/index.js
  server/src/routes/visualizationConfig.js
  server/src/services/visualizationConfigService.js
Labels: fix

#56 Feature/create visualization
  client/src/components/ ViewVisualizationMain/ViewVisualizationMain.js
  client/src/components/SelectVisualization/SelectVisualization.js
  client/src/components/SelectVisualization/styles.css
  client/src/components/ViewVisualizationSidebar/ViewVisualizationSidebar.js
  client/src/containers/TableVisualizationContainer/TableVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/constants.js
  client/src/containers/ViewVisualizationContainer/helpers/createVisualizationHelper.js
  client/src/containers/ViewVisualizationContainer/helpers/getVisualizationHelper.js
  client/src/containers/ViewVisualizationContainer/helpers/index.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/index.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/tableConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/visualizationDataHelper.js
  client/src/routes/routes.js
Labels: enhancement

#59 Fix/bar chart settings
  client/src/components/BarChart/BarChart.js
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/containers/VisualizationsListContainer/reducer.js
Labels: fix

#60 Line chart settings fix
  client/src/components/ ViewVisualizationMain/ViewVisualizationMain.js
  client/src/components/LineChart/LineChart.js
  client/src/containers/LineChartContainer/LineChartContainer.js
  client/src/containers/LineChartSettings/LineChartSettings.js
Labels: fix

#67 Feature/connect client to visualization crud
  client/src/components/SaveVisualizationModal/SaveVisualizationModal.js
  client/src/components/SelectVisualization/styles.css
  client/src/components/ViewVisualizationHeader/ViewVisualizationHeader.js
  client/src/components/ViewVisualizationHeader/styles.js
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.css
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.js
  client/src/components/ViewVisualizationMain/helper.js
  client/src/components/ViewVisualizationMain/index.js
  client/src/components/ViewVisualizationSidebar/ViewVisualizationSidebar.css
  client/src/components/index.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.css
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/actionTypes.js
  client/src/containers/ViewVisualizationContainer/actions.js
  client/src/containers/ViewVisualizationContainer/helpers/getVisualizationHelper.js
  client/src/containers/ViewVisualizationContainer/helpers/index.js
  client/src/containers/ViewVisualizationContainer/helpers/initVisualizationHelper.js
  client/src/containers/ViewVisualizationContainer/helpers/saveVisualizationHelper.js
  client/src/containers/ViewVisualizationContainer/mockData.js
  client/src/containers/ViewVisualizationContainer/reducer.js
  client/src/containers/VisualizationsListContainer/VisualizationsListContainer.js
  client/src/containers/VisualizationsListContainer/actions.js
  client/src/containers/VisualizationsListContainer/reducer.js
  client/src/containers/VisualizationsListContainer/sagas.js
  client/src/services/api/visualizationsAPI.service.js
  server/src/models/visualization.js
  server/src/services/authService.js
Labels: enhancement

#65 Add REST API docs
  client/yarn.lock
  server/index.js
  server/package.json
  server/src/docs/index.js
  server/yarn.lock
Labels: enhancement

#68 Data field selection for axes enabled
  client/src/containers/LineChartSettings/LineChartSettings.js
Labels: fix

#69 fix: unique password
  server/src/models/user.js
Labels: fix

#76 Feature/analytics page
  client/src/components/AnalyticsTabs/AnalyticsTabs.js
  client/src/components/AnalyticsTabs/AnalyticsTabsHeader/AnalyticsTabsHeader.js
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/AnalyticsTabsPanel.js
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/styles.js
  client/src/components/index.js
  client/src/containers/AnalyticsTabsContainer/AnalyticsTabsContainer.js
  client/src/containers/VisualizationsListContainer/VisualizationsListContainer.js
  client/src/containers/index.js
  client/src/pages/AnalyticsPage/AnalyticsPage.js
  client/src/pages/index.js
  client/src/routes/routes.js
Labels: enhancement

#61 Add visualization/dashboard menu added to header
  client/src/components/Header/Header.js
  client/src/components/Header/styles.css
Labels: enhancement

#75 account settings
  client/src/components/Header/Header.js
  client/src/containers/AccountSettingsContainer/AccountSettingsContainer.js
  client/src/containers/AccountSettingsContainer/styles.js
  client/src/containers/LoginPageContainer/actionTypes.js
  client/src/containers/LoginPageContainer/actions.js
  client/src/containers/LoginPageContainer/reducer.js
  client/src/containers/LoginPageContainer/sagas.js
  client/src/services/api/baseAPI.service.js
  client/src/services/api/userAPI.service.js
  server/src/config/jwt.config.js
  server/src/data/migrations/20200608225505-create-tables.js
  server/src/routes/userRoutes.js
  server/src/services/userService.js
Labels: enhancement

#80 fixed red border appearance before this field was touched
  client/src/components/LoginForm/LoginForm.js
Labels: fix

#77 Feature/add new visual to dashboard modal
  client/src/components/AddVisualizationToDashboardModal/AddVisualizationToDashboardModal.js
  client/src/components/AddVisualizationToDashboardModal/styles.css
  client/src/components/VisualizationsList/VisualizationsList.js
  client/src/components/index.js
  client/src/helpers/chooseIcon.js
Labels: enhancement

#81 Update .example.env
  server/.env.example
Labels: enhancement

#82 Feature/chart containers
  client/src/components/BarChart/BarChart.css
  client/src/components/BarChart/BarChart.js
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/LineChart/LineChart.css
  client/src/components/LineChart/LineChart.js
  client/src/containers/BarChartContainer/BarChartContainer.js
  client/src/containers/LineChartContainer/LineChartContainer.js
  client/src/containers/LineChartSettings/LineChartSettings.js
Labels: fix

#86 Feature/view dashboard page
  client/package.json
  client/src/components/AddDashboardModal/AddDashboardModal.js
  client/src/components/AddVisualizationToDashboardModal/AddVisualizationToDashboardModal.js
  client/src/components/AnalyticsTabs/AnalyticsTabs.js
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/AnalyticsTabsPanel.js
  client/src/components/BarChart/BarChart.js
  client/src/components/DashboardHeader/DashboardHeader.js
  client/src/components/DashboardHeader/DashboardHeaderEdit/index.js
  client/src/components/DashboardHeader/DashboardHeaderEdit/styles.js
  client/src/components/DashboardHeader/DashboardHeaderStatic/index.js
  client/src/components/DashboardHeader/DashboardHeaderStatic/styles.js
  client/src/components/DashboardLayout/DashboardLayout.js
  client/src/components/DashboardLayout/DashboardLayoutStyles.css
  client/src/components/Header/Header.js
  client/src/components/LineChart/LineChart.js
  client/src/components/index.js
  client/src/containers/AnalyticsTabsContainer/AnalyticsTabsContainer.js
  client/src/containers/AnalyticsTabsContainer/actions.js
  client/src/containers/AnalyticsTabsContainer/actionsTypes.js
  client/src/containers/AnalyticsTabsContainer/reducer.js
  client/src/containers/AnalyticsTabsContainer/sagas.js
  client/src/containers/DashboardContainer/DashboardContainer.js
  client/src/containers/DashboardContainer/actions.js
  client/src/containers/DashboardContainer/actionsTypes.js
  client/src/containers/DashboardContainer/helper.js
  client/src/containers/DashboardContainer/mockData.js
  client/src/containers/DashboardContainer/reducer.js
  client/src/containers/DashboardContainer/sagas.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/pages/DashboardPage/DashboardPage.js
  client/src/routes/routes.js
  client/src/services/api/dashboardsAPI.service.js
  client/src/store/reducers.js
  client/src/store/sagas.js
  client/yarn.lock
  server/src/models/dashboard.js
  server/src/routes/dashboardRoutes.js
  server/src/services/dashboardService.js
Labels: enhancement

#84 fixed minor bugs
  client/src/containers/AccountSettingsContainer/AccountSettingsContainer.js
  client/src/containers/AccountSettingsContainer/actionTypes.js
  client/src/containers/AccountSettingsContainer/actions.js
  client/src/containers/AccountSettingsContainer/reducer.js
  client/src/containers/LoginPageContainer/actionTypes.js
  client/src/containers/LoginPageContainer/actions.js
  client/src/containers/LoginPageContainer/reducer.js
  client/src/containers/LoginPageContainer/sagas.js
  client/src/store/reducers.js
Labels: fix

#85 Feature/people-page (merged with feature/admin-page)
  .vscode/settings.json
  client/src/components/AddUserModal/AddUserModal.js
  client/src/components/AddUserModal/index.js
  client/src/components/AddUserModal/styles.css
  client/src/components/GroupItem/GroupItem.js
  client/src/components/GroupList/GroupList.js
  client/src/components/GroupList/index.js
  client/src/components/GroupList/styles.js
  client/src/components/GroupListHeader/GroupListHeader.js
  client/src/components/GroupListHeader/index.js
  client/src/components/GroupListHeader/styles.js
  client/src/components/Header/Header.js
  client/src/components/Header/styles.css
  client/src/components/PeopleList/PeopleList.js
  client/src/components/PeopleList/PeopleListItem.js
  client/src/components/PeopleList/helpers/formatdate.js
  client/src/components/PeopleList/index.js
  client/src/components/PeopleList/mockPeople.js
  client/src/components/PeopleList/styles.js
  client/src/components/PeopleListHeader/PeopleListHeader.js
  client/src/components/PeopleListHeader/index.js
  client/src/components/PeopleListHeader/styles.js
  client/src/components/index.js
  client/src/containers/AdminContainer/AdminContainer.js
  client/src/containers/AdminContainer/actionTypes.js
  client/src/containers/AdminContainer/actions.js
  client/src/containers/AdminContainer/reducer.js
  client/src/containers/AdminContainer/styles.js
  client/src/containers/PeoplePageContainer/PeoplePageContainer.js
  client/src/containers/PeoplePageContainer/PeoplePageMenu.js
  client/src/containers/PeoplePageContainer/actionTypes.js
  client/src/containers/PeoplePageContainer/actions.js
  client/src/containers/PeoplePageContainer/reducer.js
  client/src/containers/PeoplePageContainer/sagas.js
  client/src/containers/PeoplePageContainer/styles.js
  client/src/containers/index.js
  client/src/pages/AdminPage/AdminPage.js
  client/src/pages/index.js
  client/src/routes/routes.js
  client/src/services/api/usersAPI.service.js
  client/src/store/reducers.js
  client/src/store/sagas.js
  server/src/data/migrations/20200608225505-create-tables.js
  server/src/data/migrations/20200608225507-create-tables.js
  server/src/models/index.js
  server/src/models/user.js
  server/src/services/authService.js
Labels: enhancement

#91 fix admin page routing
  client/src/components/Header/Header.js
  client/src/containers/AdminContainer/AdminContainer.js
  client/src/containers/AdminContainer/actionTypes.js
  client/src/containers/AdminContainer/actions.js
  client/src/containers/AdminContainer/reducer.js
  client/src/containers/AdminContainer/styles.js
  client/src/routes/routes.js
  client/src/store/reducers.js
Labels: fix

#90 Fix resize bug
  client/src/components/BarChart/BarChart.js
  client/src/components/LineChart/LineChart.js
Labels: fix

#97 feat: add env to client
  client/.env.example
  client/src/config/index.js
Labels: fix

#96 20200608225507-create-tables.js syntax error fix
  server/src/data/migrations/20200608225507-create-tables.js
Labels: fix

#89 fix/fixed user registration service
  server/src/services/authService.js
Labels: fix

#100 linter warnings fixed
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/PeopleList/PeopleList.js
  client/src/containers/LineChartSettings/LineChartSettings.js
  client/src/containers/PeoplePageContainer/PeoplePageContainer.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
Labels: fix

#92 Feature/crud databases
  client/package.json
  client/src/components/BarChart/BarChart.css
  client/src/components/BarChart/BarChart.js
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/LineChart/LineChart.css
  client/src/components/LineChart/LineChart.js
  client/src/containers/LineChartContainer/LineChartContainer.js
  client/src/containers/LineChartSettings/LineChartSettings.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
  client/src/utils/Trendline.js
  client/src/utils/trendline.js
  client/yarn.lock
  server/src/docs/index.js
  server/src/models/database.js
  server/src/models/index.js
  server/src/repositories/databaseRepository.js
  server/src/routes/databaseRoutes.js
  server/src/routes/index.js
  server/src/services/databaseService.js
Labels: enhancement

#103 sign in Button fix
  client/src/components/LoginForm/LoginForm.js
  client/src/components/LoginForm/styles.css
  client/src/containers/AccountSettingsContainer/AccountSettingsContainer.js
  client/src/containers/AccountSettingsContainer/styles.js
Labels: fix

#98 Feat/server user groups
  server/src/models/index.js
  server/src/models/userGroups.js
  server/src/models/usersUserGroups.js
  server/src/repositories/userGroupsRepository.js
  server/src/repositories/usersUserGroupsRepository.js
  server/src/routes/index.js
  server/src/routes/userGroupsRoutes.js
  server/src/services/authService.js
  server/src/services/userGroupsService.js
  server/src/services/userService.js
Labels: enhancement

#95 feat: add view-dashboard-full-screen-mode
  client/src/components/DashboardHeader/DashboardHeader.js
  client/src/components/DashboardHeader/DashboardHeaderEdit/index.js
  client/src/components/DashboardHeader/DashboardHeaderFullScreen/index.js
  client/src/components/DashboardHeader/DashboardHeaderFullScreen/styles.js
  client/src/components/DashboardHeader/DashboardHeaderStatic/index.js
  client/src/components/DashboardLayout/DashboardLayout.js
  client/src/components/DashboardLayout/DashboardLayoutStyles.css
  client/src/containers/DashboardContainer/DashboardContainer.js
  client/src/containers/DashboardContainer/helper.js
Labels: enhancement

#99 Feature/delete visualization warning
  client/src/components/AnalyticsTabs/AnalyticsTabs.js
  client/src/components/DeleteVisualizationWarning/DeleteVisualizationWarning.js
  client/src/components/ViewVisualizationHeader/ViewVisualizationHeader.js
  client/src/components/index.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  server/src/repositories/dashboardRepository.js
  server/src/services/dashboardService.js
Labels: enhancement

#107 add database button works correctly
  client/src/containers/ConnectionDatabaseContainer/ConnectionDatabaseContainer.js
  client/src/containers/ConnectionDatabaseContainer/index.js
  client/src/containers/ConnectionDatabaseContainer/styles.js
  client/src/containers/index.js
  client/src/pages/ConnectionDatabasePage/ConnectionDatabasePage.js
  client/src/pages/index.js
  client/src/routes/routes.js
  client/src/services/api/databasesAPI.service.js
Labels: enhancement

#94 Feature/deactivate activate account
  .gitignore
  client/src/components/GroupList/GroupList.js
  client/src/components/PeopleList/DeactivateUserModal.js
  client/src/components/PeopleList/PeopleList.js
  client/src/components/PeopleList/PeopleListItem.js
  client/src/components/PeopleList/PeopleTable.js
  client/src/components/PeopleList/styles.js
  client/src/containers/PeoplePageContainer/PeoplePageContainer.js
  client/src/containers/PeoplePageContainer/actionTypes.js
  client/src/containers/PeoplePageContainer/actions.js
  client/src/containers/PeoplePageContainer/sagas.js
  client/src/services/api/baseAPI.service.js
  client/src/services/api/usersAPI.service.js
  server/src/data/migrations/20200608225508-create-tables.js
  server/src/models/user.js
  server/src/services/authService.js
  server/src/services/userService.js
Labels: enhancement

#105 Feature/db manager service
  client/src/components/LineChart/LineChart.js
  server/index.js
  server/src/docs/index.js
  server/src/models/database.js
  server/src/models/dbTable.js
  server/src/models/index.js
  server/src/repositories/dbTableRepository.js
  server/src/routes/databaseRoutes.js
  server/src/routes/dbTableRoutes.js
  server/src/routes/index.js
  server/src/routes/userRoutes.js
  server/src/services/DBManager/DBManagerService.js
  server/src/services/DBManager/Managers/MongoManager.js
  server/src/services/DBManager/Managers/PostgresManager.js
  server/src/services/databaseService.js
  server/src/services/dbTableService.js
Labels: enhancement

#109 Feature/delete database
  .vscode/settings.json
  client/src/components/AnalyticsTabs/AnalyticsTabsHeader/AnalyticsTabsHeader.js
  client/src/components/DatabaseList/DatabaseList.js
  client/src/components/DatabaseList/DatabaseListItem.js
  client/src/components/DatabaseList/styles.js
  client/src/components/DatabaseListHeader/DatabaseListHeader.js
  client/src/components/DatabaseListHeader/styles.js
  client/src/components/DeleteDatabaseModal/DeleteDatabaseModal.js
  client/src/components/DeleteDatabaseModal/constants.js
  client/src/components/DeleteDatabaseModal/styles.css
  client/src/components/Header/Header.js
  client/src/components/PeopleList/PeopleList.js
  client/src/components/index.js
  client/src/containers/AdminContainer/AdminContainer.js
  client/src/containers/ConnectionDatabaseContainer/ConnectionDatabaseContainer.js
  client/src/containers/ConnectionDatabaseContainer/actionTypes.js
  client/src/containers/ConnectionDatabaseContainer/actions.js
  client/src/containers/ConnectionDatabaseContainer/index.js
  client/src/containers/ConnectionDatabaseContainer/reducer.js
  client/src/containers/ConnectionDatabaseContainer/styles.js
  client/src/containers/DatabasesPageContainer/DatabasesPageContainer.js
  client/src/containers/DatabasesPageContainer/actionTypes.js
  client/src/containers/DatabasesPageContainer/actions.js
  client/src/containers/DatabasesPageContainer/reducer.js
  client/src/containers/DatabasesPageContainer/sagas.js
  client/src/containers/index.js
  client/src/pages/ConnectionDatabasePage/ConnectionDatabasePage.js
  client/src/pages/index.js
  client/src/routes/routes.js
  client/src/services/api/databasesAPI.service.js
  client/src/store/reducers.js
  client/src/store/sagas.js
Labels: enhancement

#119 Permission cascade deletion on userGroup and dbTable deletion added
  server/src/models/dbTable.js
  server/src/models/permission.js
  server/src/models/userGroups.js
Labels: fix

#123 fix/user activation/deactivation
  client/src/components/PeopleList/PeopleList.js
  client/src/containers/PeoplePageContainer/PeoplePageContainer.js
  client/src/containers/PeoplePageContainer/actionTypes.js
  client/src/containers/PeoplePageContainer/actions.js
  client/src/containers/PeoplePageContainer/reducer.js
  client/src/containers/PeoplePageContainer/sagas.js
Labels: fix

#126 Fix switching logic on the header
  client/src/components/Header/Header.js
Labels: fix

#127 Feature/permissions page
  client/src/components/PermissionsHeader/PermissionsHeader.js
  client/src/components/PermissionsHeader/styles.js
  client/src/components/PermissionsModal/PermissionsModal.js
  client/src/components/PermissionsTable/PermissionTableAccessCell/index.js
  client/src/components/PermissionsTable/PermissionTableAccessCell/styles.js
  client/src/components/PermissionsTable/PermissionTableDataCell/index.js
  client/src/components/PermissionsTable/PermissionTableDataCell/styles.js
  client/src/components/PermissionsTable/PermissionsTable.js
  client/src/components/PermissionsTable/styles.js
  client/src/components/index.js
  client/src/containers/AdminContainer/AdminContainer.js
  client/src/containers/PermissionsContainer/PermissionsContainer.js
  client/src/containers/PermissionsContainer/actions.js
  client/src/containers/PermissionsContainer/actionsTypes.js
  client/src/containers/PermissionsContainer/config.js
  client/src/containers/PermissionsContainer/helpers.js
  client/src/containers/PermissionsContainer/reducer.js
  client/src/containers/PermissionsContainer/sagas.js
  client/src/services/api/permissionsAPI.service.js
  client/src/store/reducers.js
  client/src/store/sagas.js
  client/yarn.lock
Labels: enhancement

#115 Feature/permissions/middleware
  server/src/data/migrations/20200608225508-create-tables.js
  server/src/middlewares/permissions.js
  server/src/repositories/dbTableRepository.js
  server/src/repositories/usersUserGroupsRepository.js
  server/src/routes/databaseRoutes.js
  server/src/routes/userGroupsRoutes.js
  server/src/services/DBManager/Managers/MongoManager.js
  server/src/services/databaseService.js
  server/src/services/userGroupsService.js
  server/src/services/userService.js
  server/yarn.lock
Labels: enhancement

#128 add button to go to data sources page
  client/src/components/Header/Header.js
  client/src/components/Header/styles.css
Labels: enhancement

#129 Feature/support for mongodb
  client/src/containers/ConnectionDatabaseContainer/ConnectionDatabaseContainer.js
  server/package.json
  server/src/models/database.js
  server/src/services/DBManager/DBManagerService.js
  server/src/services/DBManager/Managers/MongoManager.js
  server/yarn.lock
Labels: enhancement

#130 Fix/minor bugs
  client/src/components/DashboardHeader/DashboardHeaderEdit/index.js
  client/src/components/DashboardHeader/DashboardHeaderEdit/styles.js
  client/src/containers/LoginPageContainer/reducer.js
  client/src/routes/routes.js
Labels: fix

#124 Feature/visualizationsWithRealData
  client/src/components/AddVisualizationToDashboardModal/AddVisualizationToDashboardModal.js
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/AnalyticsTabsPanel.js
  client/src/components/DashboardLayout/DashboardLayout.js
  client/src/components/DataSourcesTablesView/TableItem.js
  client/src/components/Header/Header.js
  client/src/components/SelectVisualization/SelectVisualization.js
  client/src/containers/DashboardContainer/DashboardContainer.js
  client/src/containers/DashboardContainer/helper.js
  client/src/containers/DashboardContainer/sagas.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initVisualizationHelper.js
  client/src/containers/ViewVisualizationContainer/helpers/saveVisualizationHelper.js
  client/src/pages/SelectVisualizationPage/SelectVisualizationPage.js
  client/src/services/api/dbTableAPI.service.js
  server/src/models/visualization.js
Labels: enhancement

#134 removed add Vis from page
  client/src/components/Header/Header.js
  client/src/routes/routes.js
Labels: fix

#132 fix: pemissions-container error if database not connected
  client/src/containers/PermissionsContainer/PermissionsContainer.js
Labels: fix

#133 Add enum for swagger database schema
  server/src/docs/index.js
Labels: fix

#125 Feature/add user by admin
  client/src/components/AddUserModal/AddUserModal.js
  client/src/components/AddUserModal/styles.css
  client/src/components/DashboardHeader/DashboardHeaderEdit/index.js
  client/src/components/DatabaseList/DatabaseListItem.js
  client/src/components/LoginForm/LoginForm.js
  client/src/components/PasswordModal/PasswordModal.js
  client/src/components/PasswordModal/styles.js
  client/src/components/PeopleList/PeopleList.js
  client/src/components/PeopleList/PeopleListItem.js
  client/src/components/PeopleList/PeopleTable.js
  client/src/components/PeopleList/helpers/selectPlaceholder.js
  client/src/components/PeopleList/styles.js
  client/src/containers/AdminContainer/AdminContainer.js
  client/src/containers/DashboardContainer/DashboardContainer.js
  client/src/containers/LoginPageContainer/reducer.js
  client/src/containers/PeoplePageContainer/PeoplePageContainer.js
  client/src/containers/PeoplePageContainer/actionTypes.js
  client/src/containers/PeoplePageContainer/actions.js
  client/src/containers/PeoplePageContainer/reducer.js
  client/src/containers/PeoplePageContainer/sagas.js
  client/src/containers/UserGroupsPageContainer/sagas.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/helpers/jwtToken.js
  client/src/routes/routes.js
  client/src/services/api/userGroupsAPI.service.js
  client/yarn.lock
  server/src/helpers/generatePassword.js
  server/src/models/index.js
  server/src/models/user.js
  server/src/repositories/userGroupsRepository.js
  server/src/routes/userGroupsRoutes.js
  server/src/routes/userRoutes.js
  server/src/services/userGroupsService.js
Labels: enhancement

#136 Fix/conflict with deactiveted users
  client/src/components/PeopleList/PeopleList.js
  client/src/components/PeopleList/PeopleListItem.js
  client/src/components/PeopleList/styles.js
Labels: fix

#137 Fix/reset permissions state
  client/src/containers/PermissionsContainer/PermissionsContainer.js
  client/src/containers/PermissionsContainer/actions.js
  client/src/containers/PermissionsContainer/actionsTypes.js
  client/src/containers/PermissionsContainer/reducer.js
Labels: fix

#138 Fix reset password when deactivate user
  client/src/components/PeopleList/PeopleList.js
  client/src/components/PeopleList/PeopleTable.js
  client/src/routes/routes.js
Labels: fix

#139 Fix add database notification
  client/src/containers/ConnectionDatabaseContainer/reducer.js
  client/src/containers/ConnectionDatabaseContainer/styles.js
Labels: fix

#135 auto-fill permissions table on new Group creation added
  server/src/services/permissionService.js
  server/src/services/userGroupsService.js
Labels: fix

#131 default ports
  client/src/containers/ConnectionDatabaseContainer/ConnectionDatabaseContainer.js
  client/src/containers/ConnectionDatabaseContainer/reducer.js
Labels: fix

#142 Fix/fixed logic of user groups
  client/src/components/GroupList/GroupList.js
  client/src/components/GroupList/RowItem.js
  client/src/containers/LoginPageContainer/sagas.js
  client/src/containers/UserGroupsPageContainer/UserGroupsPageContainer.js
  server/src/repositories/baseRepository.js
  server/src/routes/userGroupsRoutes.js
  server/src/services/userGroupsService.js
Labels: fix

#148 Fix/dashboard/charts
  client/src/components/BarChart/BarChart.js
  client/src/components/DashboardHeader/DashboardHeaderStatic/index.js
  client/src/components/LineChart/LineChart.js
  client/src/containers/DashboardContainer/DashboardContainer.js
  client/src/containers/InitialTableContainer/InitialTableContainer.js
Labels: fix

#144 Fix/admin page/add users validation
  client/src/components/AddUserModal/AddUserModal.js
  server/src/models/user.js
  server/src/routes/userRoutes.js
  server/src/services/userService.js
Labels: fix

#145 Fix/admin page/add database page path
  client/src/components/DatabaseListHeader/DatabaseListHeader.js
  client/src/containers/AdminContainer/AdminContainer.js
  client/src/containers/ConnectionDatabaseContainer/ConnectionDatabaseContainer.js
  client/src/containers/ConnectionDatabaseContainer/styles.js
  client/src/routes/routes.js
Labels: fix

#152 fix: the user cannot deactivate himself and remove himself from the a…
  client/src/components/PeopleList/PeopleList.js
  client/src/components/PeopleList/PeopleListItem.js
  client/src/components/PeopleList/PeopleTable.js
  client/src/containers/PeoplePageContainer/PeoplePageContainer.js
Labels: fix

#143 actions in PeoplePage renamed in order to differ from actions in AccountSettings
  client/src/containers/PeoplePageContainer/actionTypes.js
  client/src/containers/PeoplePageContainer/reducer.js
  client/src/containers/PeoplePageContainer/sagas.js
Labels: fix

#150 fix: visualization table is not saved when empty
  client/src/components/TableSettingsSidebar/TableSettingsSidebar.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/helpers/visualizationDataHelper.js
Labels: fix

#153 fix: save of table sorting
  client/src/components/EnhancedTable/EnhancedTableHead.js
  client/src/containers/TableVisualizationContainer/TableVisualizationContainer.js
Labels: fix

#155 fix: hide info tooltip for dashboard if description is not set
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/AnalyticsTabsPanel.js
  client/src/components/DashboardHeader/DashboardHeaderFullScreen/index.js
  client/src/components/DashboardHeader/DashboardHeaderStatic/index.js
Labels: fix

#149 feat: add the ability to return deleted columns for table visualization
  client/src/components/TableSettingsSidebar/TableSettingsSidebar.js
  client/src/components/TableSettingsSidebar/styles.css
  client/src/containers/TableVisualizationContainer/TableVisualizationContainer.js
  client/src/containers/TableVisualizationContainer/helper.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/tableConfig.js
Labels: enhancement

#154 Normalize backend responses
  server/package.json
  server/src/middlewares/errorHandlerMiddleware.js
  server/src/routes/authRoutes.js
  server/src/routes/dashboardRoutes.js
  server/src/routes/databaseRoutes.js
  server/src/routes/dbTableRoutes.js
  server/src/routes/permissionRoutes.js
  server/src/routes/userGroupsRoutes.js
  server/src/routes/userRoutes.js
  server/src/routes/visualizationRoutes.js
  server/src/services/authService.js
  server/src/services/dashboardService.js
  server/src/services/databaseService.js
  server/src/services/dbTableService.js
  server/src/services/userGroupsService.js
  server/src/services/userService.js
  server/src/services/visualizationService.js
  server/yarn.lock
Labels: enhancement

#161 asyncHandler closing bracket position fixed
  server/src/middlewares/permissions.js
  server/src/routes/databaseRoutes.js
Labels: fix

#157 fix: user group name must be at most 30 characters
  client/src/components/GroupList/UserGroupForm.js
  client/src/components/GroupList/styles.js
Labels: fix

#156 fix: the first user is administrator
  server/src/repositories/userRepository.js
  server/src/repositories/usersUserGroupsRepository.js
  server/src/services/authService.js
  server/src/services/userService.js
Labels: fix

#160 Fix/password validation
  client/src/containers/AccountSettingsContainer/AccountSettingsContainer.js
  client/src/containers/AccountSettingsContainer/styles.js
  client/src/containers/ConnectionDatabaseContainer/ConnectionDatabaseContainer.js
  server/src/helpers/generatePassword.js
Labels: fix

#158 fix/refresh current user data after changing via admin page
  client/src/containers/PeoplePageContainer/sagas.js
Labels: fix

#159 Feature/passport config
  client/src/components/GroupList/UserGroupForm.js
  client/src/containers/LoginPageContainer/index.js
  client/src/containers/LoginPageContainer/sagas.js
  client/src/helpers/callApi.js
  client/src/helpers/jwtToken.js
  client/src/services/api/baseAPI.service.js
  server/index.js
  server/src/config/jwt.config.js
  server/src/config/passportConfig.js
  server/src/config/routesWhiteListConfig.js
  server/src/docs/index.js
  server/src/helpers/tokenHelper.js
  server/src/middlewares/authenticationMiddleware.js
  server/src/middlewares/authorizationMiddleware.js
  server/src/middlewares/jwtMiddleware.js
  server/src/middlewares/passport.js
  server/src/middlewares/permissionsMiddleware.js
  server/src/middlewares/registrationMiddleware.js
  server/src/repositories/userRepository.js
  server/src/routes/authRoutes.js
  server/src/routes/databaseRoutes.js
  server/src/services/authService.js
  server/src/services/userService.js
Labels: enhancement

#167 Add sync encript
  client/src/components/GroupList/UserGroupForm.js
  client/src/containers/LoginPageContainer/index.js
  client/src/containers/LoginPageContainer/sagas.js
  client/src/helpers/jwtToken.js
  client/src/services/api/baseAPI.service.js
  server/index.js
  server/src/config/jwt.config.js
  server/src/docs/index.js
  server/src/repositories/userRepository.js
  server/src/routes/authRoutes.js
  server/src/routes/databaseRoutes.js
  server/src/services/authService.js
  server/src/services/userService.js
Labels: fix

#162 feature sync database tables
  client/src/components/DataSourcesDatasetsView/DataSourcesDatasetsView.js
  client/src/components/DataSourcesDatasetsView/DatasetItem.js
  client/src/components/DataSourcesTablesView/DataSourcesTablesView.js
  client/src/components/SelectVisualization/SelectVisualization.js
  client/src/containers/DataSourcesDatasetsContainer/DataSourcesDatasetsContainer.js
  client/src/containers/DataSourcesDatasetsContainer/actionTypes.js
  client/src/containers/DataSourcesDatasetsContainer/actions.js
  client/src/containers/DataSourcesDatasetsContainer/reducer.js
  client/src/containers/DataSourcesDatasetsContainer/sagas.js
  client/src/containers/DataSourcesTablesContainer/DataSourcesTablesContainer.js
  client/src/services/api/databasesAPI.service.js
  server/src/docs/index.js
  server/src/repositories/baseRepository.js
  server/src/repositories/databaseRepository.js
  server/src/routes/databaseRoutes.js
  server/src/services/databaseService.js
Labels: enhancement

#172 all visualizations types transferred to schema types from a remote database
  client/src/components/BarChart/BarChart.js
  client/src/components/LineChart/LineChart.js
  client/src/components/SelectVisualization/SelectVisualization.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/helpers/index.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/tableConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initVisualizationHelper.js
  server/src/services/DBManager/Managers/MongoManager.js
  server/src/services/DBManager/Managers/MySQLManager.js
  server/src/services/DBManager/Managers/PostgresManager.js
  server/src/services/DBManager/helpers/mongoDataTypeNormalizer.js
  server/src/services/DBManager/helpers/mysqlDataTypeNormalizer.js
  server/src/services/DBManager/helpers/postgresDataTypeNormalizer.js
Labels: enhancement

#170 Fix module import
  server/src/routes/databaseRoutes.js
Labels: fix

#168 Add fix to patch user data
  server/src/routes/userRoutes.js
  server/src/services/userService.js
Labels: fix

#174 Fix last login
  server/src/services/authService.js
Labels: fix

#179 Minor changes to backend responses
  server/src/repositories/userRepository.js
  server/src/routes/dashboardRoutes.js
  server/src/routes/databaseRoutes.js
  server/src/routes/dbTableRoutes.js
  server/src/routes/userGroupsRoutes.js
  server/src/routes/userRoutes.js
  server/src/routes/visualizationRoutes.js
  server/src/services/dashboardService.js
  server/src/services/databaseService.js
  server/src/services/dbTableService.js
  server/src/services/permissionService.js
  server/src/services/userGroupsService.js
  server/src/services/userService.js
  server/src/services/visualizationService.js
Labels: fix

#164 cascade deletion of visualizations configured
  server/src/models/dbTable.js
  server/src/models/visualization.js
Labels: fix

#178 Swagger docs updated
  server/src/docs/index.js
Labels: documentation

#175 Fix login deacrivated users
  server/src/services/authService.js
Labels: fix

#176 Removed extra rules from confirm password field
  client/src/containers/AccountSettingsContainer/AccountSettingsContainer.js
Labels: fix

#177 Fixed sending error message from saga
  client/src/containers/PeoplePageContainer/sagas.js
Labels: fix

#163 fix: change logic of update dashboard
  client/src/containers/DashboardContainer/DashboardContainer.js
  client/src/containers/DashboardContainer/actions.js
  client/src/containers/DashboardContainer/sagas.js
  server/src/routes/dashboardRoutes.js
  server/src/services/dashboardService.js
Labels: fix

#184 fix getDBPermissions
  server/src/services/permissionService.js
Labels: fix
