Repository BinaryStudioAcademy/bsa-2020-DaLi, pull requests merged in 2020-09, with the labels that each got.

#185 Change error message on login with incorrect email
  server/src/config/passportConfig.js
Labels: fix

#181 Feature/new config for table visualization
  client/package.json
  client/src/components/EnhancedTable/EnhancedTable.css
  client/src/components/EnhancedTable/EnhancedTable.js
  client/src/components/EnhancedTable/EnhancedTableBody.js
  client/src/components/TableSettingsSidebar/EditItem.js
  client/src/components/TableSettingsSidebar/PropertyItem.js
  client/src/components/TableSettingsSidebar/TableSettingsSidebar.js
  client/src/components/TableSettingsSidebar/styles.css
  client/src/containers/TableVisualizationContainer/helper.js
  client/yarn.lock
Labels: enhancement

#180 Feature/redactor modal on admin/people page
  client/src/components/AddUserModal/AddUserModal.js
  client/src/components/AddUserModal/index.js
  client/src/components/AddUserModal/styles.css
  client/src/components/PasswordModal/PasswordModal.js
  client/src/components/PeopleList/DeactivateUserModal.js
  client/src/components/PeopleList/PeopleList.js
  client/src/components/PeopleList/PeopleListItem.js
  client/src/components/PeopleList/PeopleTable.js
  client/src/components/PeopleList/mockPeople.js
  client/src/components/PeopleList/styles.js
  client/src/components/PeopleListHeader/PeopleListHeader.js
  client/src/components/PeopleListHeader/index.js
  client/src/components/PeopleListHeader/styles.js
  client/src/components/PeopleListModal/PeopleListModal.js
  client/src/components/PeopleListModal/modals/AddUserBody.js
  client/src/components/PeopleListModal/modals/DeactivateUserBody.js
  client/src/components/PeopleListModal/modals/ResetPasswordBody.js
  client/src/components/PeopleListModal/modals/TemporaryPasswordBody.js
  client/src/components/PeopleListModal/styles.js
  client/src/components/index.js
  client/src/containers/PeoplePageContainer/PeoplePageContainer.js
  client/src/containers/PeoplePageContainer/actionTypes.js
  client/src/containers/PeoplePageContainer/actions.js
  client/src/containers/PeoplePageContainer/reducer.js
  client/src/containers/PeoplePageContainer/sagas.js
Labels: enhancement

#186 added id to the almost all interactive ui elements(except vis settings)
  client/src/components/AnalyticsTabs/AnalyticsTabs.js
  client/src/components/GroupList/GroupList.js
  client/src/components/GroupList/RowItem.js
  client/src/components/GroupList/UserGroupForm.js
  client/src/components/GroupListHeader/GroupListHeader.js
  client/src/components/Header/Header.js
  client/src/components/LoginForm/LoginForm.js
  client/src/components/PeopleList/PeopleListItem.js
  client/src/components/PeopleListModal/modals/AddUserBody.js
  client/src/components/PeopleListModal/modals/DeactivateUserBody.js
  client/src/components/PeopleListModal/modals/ResetPasswordBody.js
  client/src/components/PeopleListModal/modals/TemporaryPasswordBody.js
  client/src/containers/PeoplePageContainer/PeoplePageMenu.js
Labels: enhancement, fix

#182 Feature/visualization sidebar and firstVisit logic
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/AnalyticsTabsPanel.js
  client/src/components/BarChart/BarChart.js
  client/src/components/DataSourcesDatasetsView/DatasetItem.js
  client/src/components/DataSourcesTablesView/TableItem.js
  client/src/components/EnhancedTable/EnhancedTable.js
  client/src/components/InitialTable/InitialTable.js
  client/src/components/LineChart/LineChart.js
  client/src/components/SaveVisualizationModal/SaveVisualizationModal.js
  client/src/components/SelectVisualization/SelectVisualization.js
  client/src/components/SelectVisualization/styles.css
  client/src/components/SelectVisualizationSidebar/SelectVisualizationSidebar.js
  client/src/components/SelectVisualizationSidebar/styles.js
  client/src/components/SignUp/SignUp.js
  client/src/components/ViewVisualizationHeader/ViewVisualizationHeader.js
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.css
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.js
  client/src/components/ViewVisualizationSidebar/ViewVisualizationSidebar.js
  client/src/components/index.js
  client/src/containers/BarChartContainer/BarChartContainer.js
  client/src/containers/LineChartContainer/LineChartContainer.js
  client/src/containers/LoginPageContainer/LoginPageContainer.js
  client/src/containers/LoginPageContainer/actionTypes.js
  client/src/containers/LoginPageContainer/actions.js
  client/src/containers/LoginPageContainer/reducer.js
  client/src/containers/LoginPageContainer/sagas.js
  client/src/containers/MapVisualizationContainer/MapVisualizationContainer.js
  client/src/containers/SingUp/SignUp.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/actionTypes.js
  client/src/containers/ViewVisualizationContainer/actions.js
  client/src/containers/ViewVisualizationContainer/helpers/index.js
  client/src/containers/ViewVisualizationContainer/helpers/initVisualizationHelper.js
  client/src/containers/ViewVisualizationContainer/helpers/visualizationDataHelper.js
  client/src/containers/ViewVisualizationContainer/reducer.js
  client/src/containers/ViewVisualizationContainer/sagas.js
  client/src/pages/SelectVisualizationPage/SelectVisualizationPage.js
  client/src/pages/index.js
  client/src/routes/routes.js
  client/src/services/api/AuthAPI.service.js
  server/src/config/routesWhiteListConfig.js
  server/src/middlewares/isFirstLogInMiddleware.js
  server/src/routes/authRoutes.js
Labels: enhancement

#183 Feature/linechart & barchart multiline
  client/src/components/BarChart/BarChart.js
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/BarChartSettings/styles.js
  client/src/components/LineChart/LineChart.js
  client/src/components/LineChartSettings/LineChartSettings.js
  client/src/components/LineChartSettings/styles.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
  server/src/services/authService.js
Labels: enhancement

#187 Fix close temporary password modal when add user
  client/src/components/PeopleListModal/PeopleListModal.js
  client/src/components/PeopleListModal/modals/AddUserBody.js
  client/src/containers/PeoplePageContainer/sagas.js
Labels: fix

#189 entity too large
  client/src/containers/ViewVisualizationContainer/helpers/saveVisualizationHelper.js
Labels: fix

#188 Add encrypt password when chenge password in account settings
  server/src/services/userService.js
Labels: fix

#191 Fix/tabs do not switch while alert is on
  client/src/components/PeopleList/PeopleList.js
  client/src/containers/PeoplePageContainer/PeoplePageContainer.js
  client/src/containers/PeoplePageContainer/actionTypes.js
  client/src/containers/PeoplePageContainer/actions.js
  client/src/containers/PeoplePageContainer/reducer.js
Labels: fix

#192 Fix/add table id to vis header
  client/src/components/DataSourcesTablesView/TableItem.js
  client/src/components/SelectVisualizationSidebar/SelectVisualizationSidebar.js
  client/src/components/ViewVisualizationHeader/ViewVisualizationHeader.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/helpers/initVisualizationHelper.js
  client/src/pages/ViewVisualizationPage/ViewVisualizationPage.js
  client/src/routes/routes.js
Labels: enhancement, fix

#193 limited label length to 20 characters
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/LineChartSettings/LineChartSettings.js
Labels: enhancement, fix

#196 Fix disabled button on Account settings page
  client/src/containers/AccountSettingsContainer/styles.js
Labels: fix

#201 denyed non-admins to create, update and delete databases
  server/src/routes/databaseRoutes.js
  server/src/services/authService.js
Labels: fix

#200 add d3 world map
  client/src/components/MapSettingsSidebar/MapSettingsSidebar.js
  client/src/components/MapVisualization/MapVisualizationGoogle.js
  client/src/components/MapVisualization/MapVisualizationGoogleHeat.js
  client/src/components/MapVisualization/MapVisualizationSchematic.js
  client/src/containers/MapVisualizationContainer/MapVisualizationContainer.js
  client/src/containers/MapVisualizationContainer/constants.js
  client/src/containers/MapVisualizationContainer/world.json
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/mapConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/visualizationDataHelper.js
Labels: enhancement

#190 Feature/collections/permissions
  client/src/components/AnalyticsTabs/AnalyticsTabs.js
  client/src/containers/ViewVisualizationContainer/helpers/rightSidebarHelper.js
  server/index.js
  server/src/config/types.js
  server/src/models/collection.js
  server/src/models/dashboard.js
  server/src/models/index.js
  server/src/models/permissionCollections.js
  server/src/models/user.js
  server/src/models/userGroups.js
  server/src/models/visualization.js
  server/src/repositories/collectionRepository.js
  server/src/repositories/dashboardRepository.js
  server/src/repositories/permissionCollectionsRepository.js
  server/src/repositories/userRepository.js
  server/src/repositories/visualizationRepository.js
  server/src/routes/collectionRoutes.js
  server/src/routes/dashboardRoutes.js
  server/src/routes/index.js
  server/src/routes/permissionCollectionsRoutes.js
  server/src/routes/visualizationRoutes.js
  server/src/services/authService.js
  server/src/services/collectionService.js
  server/src/services/dashboardService.js
  server/src/services/permissionCollectionsService.js
  server/src/services/userGroupsService.js
  server/src/services/userService.js
  server/src/services/visualizationService.js
Labels: enhancement

#195 Feature/collection/collection ui
  client/src/components/AnalyticsTabs/AnalyticsTabs.js
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/AnalyticsTabsPanel.js
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/styles.js
  client/src/components/CollectionList/CollectionList.js
  client/src/components/CollectionList/CollectionListItem.js
  client/src/components/CollectionList/styles.js
  client/src/components/CollectionModal/CollectionModal.js
  client/src/components/CollectionModal/modals/AddCollectionBody.js
  client/src/components/CollectionModal/modals/MoveCollectionBody.js
  client/src/components/CollectionModal/styles.js
  client/src/components/Header/Header.js
  client/src/components/constants/index.js
  client/src/components/index.js
  client/src/containers/AnalyticsContainer/AnalyticsContainer.js
  client/src/containers/AnalyticsContainer/actions.js
  client/src/containers/AnalyticsContainer/actionsTypes.js
  client/src/containers/AnalyticsContainer/reducer.js
  client/src/containers/AnalyticsContainer/sagas.js
  client/src/containers/AnalyticsTabsContainer/AnalyticsTabsContainer.js
  client/src/containers/AnalyticsTabsContainer/actions.js
  client/src/containers/AnalyticsTabsContainer/actionsTypes.js
  client/src/containers/AnalyticsTabsContainer/reducer.js
  client/src/containers/AnalyticsTabsContainer/sagas.js
  client/src/containers/CollectionContainer/CollectionContainer.js
  client/src/containers/CollectionContainer/styles.js
  client/src/containers/DashboardContainer/actions.js
  client/src/containers/index.js
  client/src/pages/AnalyticsPage/AnalyticsPage.js
  client/src/routes/routes.js
  client/src/services/api/baseAPI.service.js
  client/src/services/api/collectionsAPI.service.js
  client/src/services/api/dashboardsAPI.service.js
  client/src/services/api/visualizationsAPI.service.js
  client/src/store/reducers.js
  client/src/store/sagas.js
  server/src/models/collection.js
  server/src/repositories/collectionRepository.js
  server/src/routes/collectionRoutes.js
  server/src/routes/index.js
  server/src/services/collectionService.js
  server/src/services/permissionCollectionsService.js
Labels: enhancement

#147 fix: bug of create visualization
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/actionTypes.js
  client/src/containers/ViewVisualizationContainer/actions.js
  client/src/containers/ViewVisualizationContainer/reducer.js
  client/src/containers/ViewVisualizationContainer/sagas.js
  server/src/routes/authRoutes.js
  server/src/services/authService.js
  server/src/services/dbTableService.js
Labels: fix

#206 Fix collections hover effect
  client/src/components/CollectionList/styles.js
Labels: fix

#209 Fixed crash app when creating a mini bar chart
  client/src/components/EnhancedTable/EnhancedTableBody.js
Labels: fix

#208 Fix/dasboard visualizations fetching
  client/src/components/AddVisualizationToDashboardModal/AddVisualizationToDashboardModal.js
  client/src/components/BarChart/BarChart.js
  client/src/components/FilterBar/FilterFieldsList.js
  client/src/components/FilterBar/styles.js
  client/src/components/InitialTable/InitialTable.js
  client/src/components/SelectVisualizationSidebar/SelectVisualizationSidebar.js
  client/src/components/SelectVisualizationSidebar/styles.js
  client/src/components/ViewVisualizationHeader/ViewVisualizationHeader.js
  client/src/containers/InitialTableContainer/InitialTableContainer.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initVisualizationHelper.js
  client/src/containers/ViewVisualizationContainer/helpers/visualizationDataHelper.js
  server/src/services/dbTableService.js
Labels: fix

#211 id to analytics
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/AnalyticsTabsPanel.js
  client/src/components/CollectionModal/modals/MoveCollectionBody.js
  client/src/containers/CollectionContainer/CollectionContainer.js
Labels: fix

#212 30 char is max for table title
  client/src/components/TableSettingsSidebar/EditItem.js
  client/src/components/TableSettingsSidebar/TableSettingsSidebar.js
Labels: fix

#219 Fix: disabled some settings for visualizations
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/LineChartSettings/LineChartSettings.js
  client/src/components/TableSettingsSidebar/PropertyItem.js
  client/src/components/TableSettingsSidebar/TableSettingsSidebar.js
  server/yarn.lock
Labels: fix

#221 Feat/filter bar v2
  client/src/components/FilterBar/FilterBar.js
  client/src/components/FilterBar/FilterForms/DateFilterForm.js
  client/src/components/FilterBar/FilterForms/NumberFilterForm.js
  client/src/components/FilterBar/FilterForms/StringFilterForm.js
  client/src/components/ViewVisualizationHeader/ViewVisualizationHeader.js
  server/src/services/DBManager/Managers/PostgresManager.js
Labels: enhancement

#207 Add more special symbols to password form
  client/src/containers/SingUp/SignUp.js
Labels: fix

#210 Feature/users access
  client/src/containers/AnalyticsContainer/actionsTypes.js
  client/src/containers/AnalyticsContainer/reducer.js
  client/src/containers/AnalyticsContainer/sagas.js
  client/src/containers/DashboardContainer/DashboardContainer.js
  client/src/containers/DashboardContainer/actions.js
  client/src/containers/DashboardContainer/actionsTypes.js
  client/src/containers/DashboardContainer/reducer.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/actionTypes.js
  client/src/containers/ViewVisualizationContainer/actions.js
  client/src/containers/ViewVisualizationContainer/reducer.js
  client/src/containers/ViewVisualizationContainer/sagas.js
  server/src/middlewares/userAccessMiddleware.js
  server/src/repositories/collectionRepository.js
  server/src/repositories/dashboardRepository.js
  server/src/repositories/permissionCollectionsRepository.js
  server/src/repositories/visualizationRepository.js
  server/src/routes/collectionRoutes.js
  server/src/routes/dashboardRoutes.js
  server/src/routes/visualizationRoutes.js
Labels: enhancement

#213 User update middleware extended
  server/src/middlewares/denyAccesForNonAdminsMiddleware.js
Labels: fix

#220 Barchart stacked
  client/src/components/BarChart/BarChart.css
  client/src/components/BarChart/BarChart.js
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/BarChartSettings/styles.js
  client/src/components/ColorPicker/ColorPicker.js
  client/src/components/ColorPicker/styles.js
  client/src/components/LineChart/LineChart.css
  client/src/components/LineChart/LineChart.js
  client/src/components/LineChartSettings/LineChartSettings.js
  client/src/components/SummarizeBar/SummarizeBar.js
  client/src/components/index.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
  server/src/routes/databaseRoutes.js
Labels: enhancement

#217 remove table id from header
  client/src/components/ViewVisualizationHeader/ViewVisualizationHeader.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
Labels: fix

#222 Fix/visualisations settings
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/LineChartSettings/LineChartSettings.js
Labels: fix

#223 Fix/y scale calculation
  client/src/components/BarChart/BarChart.js
  client/src/components/LineChart/LineChart.js
Labels: fix

#227 redesign filters and summarize
  client/public/no_data.png
  client/src/components/FilterBar/FilterBar.js
  client/src/components/FilterBar/FilterFieldsList.js
  client/src/components/FilterBar/FilterForms/DateFilterForm.js
  client/src/components/FilterBar/FilterForms/NumberFilterForm.js
  client/src/components/FilterBar/FilterForms/StringFilterForm.js
  client/src/components/FilterBar/styles.js
  client/src/components/SummarizeBar/GroupByList.js
  client/src/components/SummarizeBar/SummarizeBar.js
  client/src/components/SummarizeBar/styles.js
  client/src/components/ViewVisualizationHeader/ViewVisualizationHeader.js
  client/src/components/ViewVisualizationHeader/styles.js
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.js
  client/src/containers/InitialTableContainer/InitialTableContainer.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/helpers/visualizationDataHelper.js
  client/src/containers/ViewVisualizationContainer/reducer.js
Labels: enhancement

#228 Feature/redesign
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/no_data.png
  client/src/App.css
  client/src/components/AddVisualizationToDashboardModal/AddVisualizationToDashboardModal.js
  client/src/components/AddVisualizationToDashboardModal/styles.css
  client/src/components/AnalyticsTabs/AnalyticsTabs.js
  client/src/components/AnalyticsTabs/AnalyticsTabsHeader/AnalyticsTabsHeader.js
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/AnalyticsTabsPanel.js
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/styles.js
  client/src/components/CollectionList/CollectionList.js
  client/src/components/CollectionList/CollectionListItem.js
  client/src/components/CollectionModal/modals/MoveCollectionBody.js
  client/src/components/CollectionModal/styles.js
  client/src/components/DashboardHeader/DashboardHeaderEdit/styles.js
  client/src/components/DashboardHeader/DashboardHeaderFullScreen/styles.js
  client/src/components/DashboardLayout/DashboardLayoutStyles.css
  client/src/components/FilterBar/FilterBar.js
  client/src/components/FilterBar/FilterFieldsList.js
  client/src/components/FilterBar/FilterForms/DateFilterForm.js
  client/src/components/FilterBar/FilterForms/NumberFilterForm.js
  client/src/components/FilterBar/FilterForms/StringFilterForm.js
  client/src/components/FilterBar/styles.js
  client/src/components/Header/styles.css
  client/src/components/Modal/Modal.js
  client/src/components/Modal/styles.css
  client/src/components/PeopleList/PeopleList.js
  client/src/components/PeopleListHeader/PeopleListHeader.js
  client/src/components/SignUp/SignUp.js
  client/src/components/SummarizeBar/GroupByList.js
  client/src/components/SummarizeBar/SummarizeBar.js
  client/src/components/SummarizeBar/styles.js
  client/src/components/ViewVisualizationHeader/ViewVisualizationHeader.js
  client/src/components/ViewVisualizationHeader/styles.js
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.js
  client/src/components/constants/index.js
  client/src/containers/InitialTableContainer/InitialTableContainer.js
  client/src/containers/LoginPageContainer/LoginPageContainer.js
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.css
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
  client/src/containers/ViewVisualizationContainer/helpers/visualizationDataHelper.js
  client/src/containers/ViewVisualizationContainer/reducer.js
  client/src/containers/WidgetsContainer/WidgetsContainer.js
  client/src/containers/WidgetsContainer/styles.js
  client/src/containers/index.js
  client/src/helpers/chooseIcon.js
  client/src/pages/HomePage/HomePage.js
  client/src/pages/index.js
  client/src/routes/routes.js
  client/src/theme/theme.js
Labels: enhancement

#225 added formating date, and now long values wrapping to the next line
  client/src/components/BarChart/BarChart.js
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/LineChart/LineChart.js
  client/src/components/LineChartSettings/LineChartSettings.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
Labels: fix

#229 Revert "added formating date, and now long values wrapping to the next line"
  client/src/components/BarChart/BarChart.js
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/LineChart/LineChart.js
  client/src/components/LineChartSettings/LineChartSettings.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
Labels: fix

#230 Fix/vis values
  client/src/components/BarChart/BarChart.js
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/LineChart/LineChart.js
  client/src/components/LineChartSettings/LineChartSettings.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
Labels: fix

#231 Feature/redesign
  client/src/components/AnalyticsTabs/AnalyticsTabsPanel/AnalyticsTabsPanel.js
  client/src/components/FilterBar/FilterBar.js
  client/src/components/FilterBar/FilterForms/NumberFilterForm.js
  client/src/components/FilterBar/styles.js
  client/src/components/SaveVisualizationModal/styles.css
  client/src/components/SummarizeBar/GroupByList.js
  client/src/components/SummarizeBar/SummarizeBar.js
  client/src/components/SummarizeBar/styles.js
  client/src/containers/WidgetsContainer/WidgetsContainer.js
  client/src/theme/theme.js
Labels: fix

#232 Feature/redesign
  client/src/components/PermissionsTable/PermissionsTable.js
  client/src/components/PermissionsTable/styles.js
  client/src/containers/PeoplePageContainer/styles.js
  client/src/containers/PermissionsContainer/PermissionsContainer.js
  client/src/containers/PermissionsContainer/styles.js
Labels: enhancement

#233 Feature/charts settings redesign
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/BarChartSettings/styles.js
  client/src/components/ColorPicker/ColorPicker.js
  client/src/components/ColorPicker/styles.js
  client/src/components/LineChart/LineChart.js
  client/src/components/LineChartSettings/LineChartSettings.js
  client/src/components/LineChartSettings/styles.js
  client/src/components/SelectVisualizationSidebar/styles.js
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.css
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
Labels: enhancement

#235 Feature/redesign
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/BarChartSettings/styles.js
  client/src/components/ColorPicker/ColorPicker.js
  client/src/components/ColorPicker/styles.js
  client/src/components/LineChart/LineChart.js
  client/src/components/LineChartSettings/LineChartSettings.js
  client/src/components/LineChartSettings/styles.js
  client/src/components/PermissionsHeader/PermissionsHeader.js
  client/src/components/PermissionsHeader/styles.js
  client/src/components/SelectVisualizationSidebar/styles.js
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.css
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.js
  client/src/containers/PermissionsContainer/PermissionsContainer.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
Labels: enhancement

#234 Feature/charts settings redesign
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/BarChartSettings/styles.js
  client/src/components/ColorPicker/ColorPicker.js
  client/src/components/ColorPicker/styles.js
  client/src/components/LineChart/LineChart.js
  client/src/components/LineChartSettings/LineChartSettings.js
  client/src/components/LineChartSettings/styles.js
  client/src/components/SelectVisualizationSidebar/styles.js
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.css
  client/src/components/ViewVisualizationMain/ViewVisualizationMain.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/barChartConfig.js
  client/src/containers/ViewVisualizationContainer/helpers/initConfigsHelper/lineChartConfig.js
Labels: enhancement

#237 quick fix
  client/src/components/CollectionModal/modals/MoveCollectionBody.js
  client/src/components/CollectionModal/styles.js
Labels: fix

#239 turned off email validation
  server/src/middlewares/denyAccesForNonAdminsMiddleware.js
  server/src/services/userService.js
Labels: fix

#241 trendline disabled
  client/src/components/BarChart/BarChart.js
  client/src/components/BarChartSettings/BarChartSettings.js
  client/src/components/LineChart/LineChart.js
  client/src/components/LineChartSettings/LineChartSettings.js
Labels: fix

#242 Map chart sidebar redesign
  client/src/components/MapSettingsSidebar/MapSettingsSidebar.js
  client/src/components/MapSettingsSidebar/styles.js
Labels: enhancement

#243 redesign
  client/src/App.css
  client/src/components/GroupList/UserForm.js
  client/src/components/GroupList/UserGroupForm.js
  client/src/components/GroupList/styles.js
  client/src/components/PeopleList/styles.js
  client/src/containers/AccountSettingsContainer/AccountSettingsContainer.js
  client/src/containers/AccountSettingsContainer/styles.js
  client/src/containers/PermissionsContainer/PermissionsContainer.js
  client/src/containers/PermissionsContainer/styles.js
Labels: enhancement

#245 fix/double-notification-on-update-vizualization
  client/src/containers/ViewVisualizationContainer/ViewVisualizationContainer.js
Labels: fix
